# Generated by Django 5.0.6 on 2024-11-04 17:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sale_delete_sales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale',
            new_name='Sales',
        ),
    ]
